name: BuildMap
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - shell: pwsh
        run: ./Generate-Map.ps1
      - run: |
          mkdir maps
          cp mymap.svg maps/
          cp mymapus.svg maps/
      - name: Install Inkscape
        run: sudo apt-get install -y inkscape
      - name: Convert to rasters
        run: |
          inkscape --export-filename=maps/mymap.png -w 4960 -y 0 mymap.svg
          inkscape --export-filename=maps/mymapthb.png -w 800 -y 0 mymap.svg
          inkscape --export-filename=maps/mymapus.png -w 4960 -y 0 mymapus.svg
          inkscape --export-filename=maps/mymapusthb.png -w 800 -y 0 mymapus.svg
      - uses: actions/upload-artifact@v3
        with: 
          name: maps
          path: maps